# Generated by Django 3.0.4 on 2020-06-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_information_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
