# Generated by Django 3.0.4 on 2020-06-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0003_delete_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('enail', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=50)),
                ('hobby', models.CharField(max_length=50)),
                ('massage', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
