# Generated by Django 3.0.4 on 2020-06-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
    ]
