# Generated by Django 3.0.4 on 2020-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anima',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
