# Generated by Django 3.0.4 on 2020-06-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anima', '0002_anima_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
